resources:

  - name: nodeRepoResource
    type: gitRepo
    repoPath: manishas/basic-node
    configuration:
      integrationName: manishas_github
      buildOn:
         commit: true
         pullRequest: true
         pullRequestClose: false
         release: true
         tagPush: true
    initialVersion:
      sha: master


pipelines:
  - name: test_pipeline_1
    steps:
      - name: main_step
        type: bash
        setup:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16nodall
                tag:  v7.1.4
        triggeredBy:
          steps:
            - nodeRepoResource
        execution:
          onStart:
            - echo "Prepping build environment"
          onExecute:
            - compare_git --resource nodeRepoResource
            - cd "$(cat $STEP_JSON_PATH | jq -r .'resources.nodeRepoResource.resourcePath')"
            - switch_env nodejs 0.12
            - npm install
            - cd tests
            - ../node_modules/.bin/mocha --recursive "**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=../testresults.xml
            - ../node_modules/.bin/istanbul --include-all-sources cover -root "../routes" ../node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "**/*.spec.js"
            - ../node_modules/.bin/istanbul report cobertura --dir ../coverageReport
            - cd .. && ls
            - save_tests testresults.xml
            - cache_files shippable.yml myYml
            - ls -R $RUN_DIR
        #    - save_tests $(cat $STEP_JSON_PATH | jq -r .'resources.nodeRepoResource.resourcePath') #testresults.xml
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"
          onCancel:
            - echo "Someone cancelled the job"
